
[entryPoints]
  [entryPoints.http]
  address = ":8001"

[file]

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://127.0.0.1:5000"
    [backends.backend1.servers.server2]
    url = "http://127.0.0.1:5001"
    [backends.backend1.servers.server3]
    url = "http://127.0.0.1:5002"
    [backends.backend1.servers.server4]
    url = "http://127.0.0.1:5003"

[frontends]
  [frontends.frontend1]
  backend = "backend1"
    [frontends.frontend1.routes.test_1]
    rule = "Host:localhost"
